// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFzLYcmKuZt5w9Sah_swmapCBJQWGCaeE',
    appId: '1:688253960963:web:a106a185d652ec2f449f36',
    messagingSenderId: '688253960963',
    projectId: 'swift-cafe-app-ui',
    authDomain: 'swift-cafe-app-ui.firebaseapp.com',
    storageBucket: 'swift-cafe-app-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgQ_9fI0ttnm-R4gqcPaO_DY3-Hwpxuo',
    appId: '1:688253960963:android:99687ce96e2bfffc449f36',
    messagingSenderId: '688253960963',
    projectId: 'swift-cafe-app-ui',
    storageBucket: 'swift-cafe-app-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVUbUHAvaelhJ4l7oH7mcEglUkNXF_5E8',
    appId: '1:688253960963:ios:f82d6cdeaa03ea81449f36',
    messagingSenderId: '688253960963',
    projectId: 'swift-cafe-app-ui',
    storageBucket: 'swift-cafe-app-ui.appspot.com',
    iosBundleId: 'com.example.seequenzeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVUbUHAvaelhJ4l7oH7mcEglUkNXF_5E8',
    appId: '1:688253960963:ios:f82d6cdeaa03ea81449f36',
    messagingSenderId: '688253960963',
    projectId: 'swift-cafe-app-ui',
    storageBucket: 'swift-cafe-app-ui.appspot.com',
    iosBundleId: 'com.example.seequenzeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFzLYcmKuZt5w9Sah_swmapCBJQWGCaeE',
    appId: '1:688253960963:web:322ec762cb2b461d449f36',
    messagingSenderId: '688253960963',
    projectId: 'swift-cafe-app-ui',
    authDomain: 'swift-cafe-app-ui.firebaseapp.com',
    storageBucket: 'swift-cafe-app-ui.appspot.com',
  );
}
